<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Title>SDSL</Title>
        <Description>Seal Dynamic Scripting Language is a scripting langauge built in C# for fun!</Description>
        <Copyright>MIT License</Copyright>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageProjectUrl>https://github.com/TheSnowDoggo/SDSL/</PackageProjectUrl>
        <RepositoryUrl>https://github.com/TheSnowDoggo/SDSL/</RepositoryUrl>
        <RepositoryType>github</RepositoryType>
        <PackageTags>scripting-language</PackageTags>
        <PackageReleaseNotes>Initial release.</PackageReleaseNotes>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <NeutralLanguage>en</NeutralLanguage>
    </PropertyGroup>
    
    <ItemGroup>
        <None Include="LICENSE" Pack="true" PackagePath=""/>
        <None Include="README.md" Pack="true" PackagePath=""/>
    </ItemGroup>

</Project>
